### ISSUE TITLE
[BUG] VSIX extension not signed 0.0.16

### ISSUE THREAD

**Issue by sdnfr** [jvalue/jayvee#362]
## Steps to reproduce
1. Download extension from github https://github.com/jvalue/jayvee/releases/tag/v0.0.16-alpha
2. Install vsix extension
## Description
- Expected: 
- Actual: Install extension failed: Error: 
6/15/2023 6:35:52 PM - Extension Details...
6/15/2023 6:35:52 PM - 	Identifier         : jayvee
6/15/2023 6:35:52 PM - 	Name               : Jayvee
6/15/2023 6:35:52 PM - 	Author             : undefined
6/15/2023 6:35:52 PM - 	Version            : 0.0.16
6/15/2023 6:35:52 PM - 	Description        : Support for the Jayvee language
6/15/2023 6:35:52 PM - 	Locale             : en-US
6/15/2023 6:35:52 PM - 	MoreInfoURL        : 
6/15/2023 6:35:52 PM - 	InstalledByMSI     : False
6/15/2023 6:35:52 PM - 	SupportedFrameworkVersionRange : [0.0,2147483647.2147483647]
6/15/2023 6:35:52 PM - 	SignatureState     : Unsigned
6/15/2023 6:35:52 PM - 	Supported Products : 
6/15/2023 6:35:52 PM - 		Microsoft.VisualStudio.Code
6/15/2023 6:35:52 PM - 			Version : 
6/15/2023 6:35:52 PM - 			ProductArchitecture : x86
6/15/2023 6:35:52 PM - 	References         : 
6/15/2023 6:35:52 PM - Signature Details...
6/15/2023 6:35:52 PM - 	Extension is not signed.
6/15/2023 6:35:52 PM - VSIXInstaller.NoApplicableSKUsException: One or more extensions are for Visual Studio Code. Try installing them in Visual Studio Code.
   at VSIXInstaller.ExtensionService.GetInstallableDataImpl(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionService.GetInstallableData(String vsixPath, String extensionPackParentName, Boolean isRepairSupported, IStateData stateData, IEnumerable`1& skuData)
   at VSIXInstaller.ExtensionPackService.IsExtensionPack(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.ExtensionPackService.ExpandExtensionPackToInstall(IStateData stateData, Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize(Boolean isRepairSupported)
   at VSIXInstaller.App.Initialize()
   at System.Threading.Tasks.Task`1.InnerInvoke()
   at System.Threading.Tasks.Task.Execute()

**Comment by georg-schwarz** [comment]
Thank you very much for reporting this bug! 

> 2. Install vsix extension
How did you install the extension? Via CLI or via the VSCode UI?

**Comment by stefandnfr** [comment]
On Windows, installing the extension via [double clicking](https://learn.microsoft.com/en-us/visualstudio/ide/finding-and-using-visual-studio-extensions?view=vs-2022#install-without-using-the-manage-extensions-dialog-box) does not seem to work. However, when installing it via Extensions > Manage Extensions  directly in VS Code, it works.
